BattleShips.WebUI/Models/RatingDataModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BattleShips.WebUI.Models
{
    public class RatingDataModel
    {
        public string UserName { get; set; }
        public int Score { get; set; }
    }
}

BattleShips.WebUI/Controllers/BattleFieldController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BattleShips.Entities;

namespace BattleShips.WebUI.Controllers
{
    public class BattleFieldController : Controller
    {
        private static FakeStorageData data = new FakeStorageData();
        // GET: BattleField
        public ActionResult Field()
        {
            ViewBag.FieldSize = 10;
            return View();
        }
        [HttpPost]
        public ActionResult GetShipsPosition(string positions)
        {
            data.ShipsPosition = positions;
            return Json(new object());
        }
        [HttpPost]
        public ActionResult ResponseOnFire(int id)
        {
            return Json(new { cellValue = data.ShipsPosition[id] });
        }
    }
}

BattleShips.WebUI/Controllers/HomeController.cs
using BattleShips.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BattleShips.WebUI.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult PlayerRating()
        {
            List<RatingDataModel> ratingData = new List<RatingDataModel>();
            ratingData.Add(new RatingDataModel()
            {
                UserName = "Pupkin",
                Score = 2300
            });
            ratingData.Add(new RatingDataModel()
            {
                UserName = "Bulkin",
                Score = 2220
            });
            ratingData.Add(new RatingDataModel()
            {
                UserName = "Zubkin",
                Score = 1500
            });
            ratingData.Add(new RatingDataModel()
            {
                UserName = "Nagibator",
                Score = 1000
            });
            return View(ratingData);
        }
        [HttpGet]
        public ActionResult Registration()
        {
            return View();
        }
    }
}

BattleShips.WebUI/Views/BattleField/Field.cshtml
@{
    int fieldSize = ViewBag.FieldSize;
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/libs/jquery/jquery-2.1.4.js"></script>
    <script src="~/Scripts/pages/MoveShips.js"></script>
    <!--<script src="~/Scripts/pages/Fire.js"></script>-->
    <script src="~/Scripts/pages/Connect.js"></script>
    <script src="~/Scripts/libs/SignalR/jquery.signalR-2.2.0.min.js"></script>
    <script src="~/signalr/hubs"></script>
    <link href="@Url.Content("/css/BattleField.css")" rel="stylesheet" type="text/css" />
    <title>Index</title>
</head>
<body>
    <div class="fields">
        <br /> <br />
        <table style="font-family:'Comic Sans MS', Arial; margin:auto; font-size: 13px;">
            @for (int i = 0; i < fieldSize + 1; ++i)
            {
                <tr class="">
                    @for (int j = 0; j < fieldSize + 1; ++j)
                    {
                        if (j == 1 && i == 1)
                        {
                            <th class="" colspan="10" rowspan="10">
                                <table class="battle_field" id="enemyField">
                                    @for (int k = 0; k < fieldSize; ++k)
                                    {
                                        <tr class="battle_field">
                                            @for (int L = 0; L < fieldSize; ++L)
                                            {
                                                <th class="battle_field" data-id="@Convert.ToInt32(@k + @L.ToString())">
                                                    <!--
                                                    <form method="post">
                                                        <input type="submit" value="" class="cell" />
                                                    </form>
                                                    -->
                                                    <button class="cell" data-id="@Convert.ToInt32(@k + @L.ToString())" />
                                                </th>
                                            }
                                        </tr>
                                    }
                                </table>
                            </th>
                            j = fieldSize;
                        }
                        else if (i == 0 && j > 0)
                        {
                            <th class="">@Convert.ToChar(@j + 64)</th>
                        }
                        else if (j == 0 && i != 0)
                        {
                            <th class="">@i</th>
                        }
                        else if (j == 0 && i == 0)
                        {
                            <th class=""></th>
                        }
                    }
                </tr>
            }
        </table>

    </div>
    <div class="timer">Turn
        <div id="turn"></div>
    </div>
    <div class="fields">
        <br /> <br />
        <table class="" style="font-family:'Comic Sans MS',Arial; margin:auto; font-size: 13px;">
            @for (int i = 0; i < fieldSize + 1; ++i)
            {
                <tr class="">
                    @for (int j = 0; j < fieldSize + 1; ++j)
                    {
                        if (j == 1 && i == 1)
                        {
                            <th class="" colspan="10" rowspan="10">
                                <table class="battle_field" id="yourField">
                                    @for (int k = 0; k < fieldSize; ++k)
                                    {
                                        <tr class="battle_field">
                                            @for (int L = 0; L < fieldSize; ++L)
                                            {
                                                <th class="battle_field" id="@(k.ToString() + L)" data-id="@Convert.ToInt32(@k + @L.ToString())">
                                                </th>
                                            }
                                        </tr>
                                    }
                                </table>
                            </th>
                            j = fieldSize;
                        }
                        else if (i == 0 && j > 0)
                        {
                            <th class="">@Convert.ToChar(@j + 64)</th>
                        }
                        else if (j == 0 && i != 0)
                        {
                            <th class="">@i</th>
                        }
                        else if (j == 0 && i == 0)
                        {
                            <th></th>
                        }
                    }
                </tr>
            }
        </table>
    </div>
    <div class="clear"></div>
    <div class="userList"></div>
    <div class="left"><input type="button" style="margin-right:10px" value="Start" id="sendShipsCord" disabled/></div>
    <div class="right">
        @{
            int shipSize = 4, shipId = 0, shipCount = 1, maxShips = 10;

            while (maxShips != 0)
            {
                for (int i = 0; i < shipCount; i++)
                {
                    --maxShips;
                    <div class="ship" id="@shipId">
                        @for (int j = 0; j < shipSize; j++)
                        {
                            <div class="shipCell"></div>
                        }
                    </div>
                    <div class="space"></div>
                    ++shipId;
                }
                ++shipCount;
                --shipSize;
                <div class="clear"></div>
            }
        }
    </div>
    <input id="hdId" type="hidden" />
    <input id="shipsPosition" type="hidden" />
    <!--
    <div class="clear"></div>
    <div class="ship" id="4">
        <div class="shipCell"></div>
        <div class="shipCell"></div>
        <div class="shipCell"></div>
        <div class="shipCell"></div>
    </div>
    <div class="clear"></div>
    <div class="ship" id="3">
        <div class="shipCell"></div>
        <div class="shipCell"></div>
        <div class="shipCell"></div>
    </div>
    <div class="clear"></div>
    <div class="ship" id="2">
        <div class="shipCell"></div>
        <div class="shipCell"></div>
    </div>
    <div class="clear"></div>
    <div class="ship" id="1">
        <div class="shipCell"></div>
    </div>
        -->
</body>
</html>

BattleShips.WebUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@section scripts
    {
        <script src="~/Scripts/pages/hideBlock.js"></script>
    }

<div class="content">
    <ul>
        <li>
            @Html.ActionLink("Go to Battle", "Field", "BattleField")
        </li>
        <li>
            @Html.ActionLink("Player Ratin", "PlayerRating", "Home")

        </li>
        <li>
            @Html.ActionLink("Sing Up", "Registration", "Home")
        </li>
        <li>
            <a href="" onclick="hideBlock('lForm');return (false)">Sing In</a>
        </li>
    </ul>
    <form method="post">
        <div class="loginForm" style="height: 100px; display: none;" id="lForm">
            <div class="loginForm">
                <input type="textarea" placeholder="username" name="userName" />
            </div>
            <div class="loginForm">
                <input type="password" placeholder="password" name="pass" />
            </div>
            <div class="loginForm">
                <input type="submit" id="btnLogin" title="Login" value="" />
            </div>
        </div>
    </form>
</div>

BattleShips.WebUI/Views/Home/PlayerRating.cshtml
@using BattleShips.WebUI.Models;

@{ 
    @model List<RatingDataModel>
}

@{
    ViewBag.Title = "PlayerRating";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="content">
    <div class="ratingTable">
        @for (int i = 0; i < Model.Count; ++i)
        {
            <div class="ratingPlace">
                @(i + 1)
            </div>
            <div class="ratingName">
                @Model[i].UserName
            </div>
            <div class="ratingScore">
                @Model[i].Score
            </div>
        }
    </div>
</div>

BattleShips.WebUI/Views/Home/Registration.cshtml
@{
    ViewBag.Title = "Registration";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="content">
    <div class="regForm">
        <form method="post">
            <div class="regFormNameItem">
                User name:
            </div>
            <div class="regFormInput">
                <input type="textarea" name="userName" />
            </div>
            <div class="regFormNameItem">
                E-mail:
            </div>
            <div class="regFormInput">
                <input type="textarea" name="email" />
            </div>
            <div class="regFormNameItem">
                Password:
            </div>
            <div class="regFormInput">
                <input type="password" name="pass" />
            </div>
            <div class="regFormNameItem">
                Confirm pass:
            </div>
            <div class="regFormInput">
                <input type="password" name="confPass" />
            </div>
            <div class="regFormInput" style="margin:0; padding: 0">
                <input type="submit" value="Registrate" style="margin:0px; outline: none" />
            </div>
        </form>
    </div>
</div>

BattleShips.WebUI/Views/Shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Battle Ships</title>
    <link href="~/css/myStyles.css" rel="stylesheet" />
    <script src="~/Scripts/libs/jquery/jquery-2.1.4.js"></script>
    @RenderSection("scripts", false)
</head>
<body>
    <div class="wrapper">
        <div class="logo">
            <h1>Battle Ships</h1>
            <hr />
        </div>

            @RenderBody() 

        <div class="footer">
            <hr />
            Design by Fedas Maksym. 2015<br />
            E-mail: maxym.fedas@gmail.com
        </div>
    </div>
</body>
</html>